export const jobTitles = [
    "Software Engineer", "Data Scientist", "Product Manager", "Marketing Specialist",
    "Financial Analyst", "Human Resources Manager", "Customer Service Representative",
    "Graphic Designer", "Sales Representative", "Operations Manager", "Teacher",
    "Nurse", "Accountant", "Lawyer", "Chef", "Electrician", "Plumber", "Architect",
    "Photographer", "Journalist", "Police Officer", "Firefighter", "Pilot",
    "Veterinarian", "Dentist", "Psychologist", "Librarian", "Social Worker",
    "Real Estate Agent", "Insurance Agent", "Pharmacist", "Physical Therapist",
    "Occupational Therapist", "Speech Therapist", "Dietitian", "Personal Trainer",
    "Yoga Instructor", "Life Coach", "Career Counselor", "Wedding Planner",
    "Event Coordinator", "Travel Agent", "Tour Guide", "Hotel Manager",
    "Restaurant Manager", "Bartender", "Barista", "Florist", "Landscaper",
    "Interior Designer", "Fashion Designer", "Tailor", "Hairdresser", "Makeup Artist",
    "Nail Technician", "Massage Therapist", "Chiropractor", "Acupuncturist",
    "Nutritionist", "Fitness Instructor", "Dance Instructor", "Music Teacher",
    "Art Teacher", "Drama Teacher", "ESL Teacher", "Special Education Teacher",
    "Preschool Teacher", "Daycare Worker", "Nanny", "Tutor", "Professor",
    "Research Scientist", "Lab Technician", "Biologist", "Chemist", "Physicist",
    "Astronomer", "Geologist", "Environmental Scientist", "Meteorologist",
    "Zoologist", "Marine Biologist", "Botanist", "Archaeologist", "Anthropologist",
    "Historian", "Economist", "Sociologist", "Political Scientist", "Philosopher",
    "Theologian", "Pastor", "Priest", "Rabbi", "Imam", "Monk", "Nun",
    "Missionary", "Social Media Manager", "Content Creator", "Influencer",
    "Blogger", "Podcaster", "YouTuber", "Twitch Streamer", "E-sports Player",
    "Game Developer", "UX Designer", "UI Designer", "Web Developer",
    "Mobile App Developer", "Systems Administrator", "Network Engineer",
    "Cybersecurity Analyst", "Database Administrator", "Cloud Architect",
    "DevOps Engineer", "Machine Learning Engineer", "AI Researcher",
    "Robotics Engineer", "Biomedical Engineer", "Aerospace Engineer",
    "Civil Engineer", "Mechanical Engineer", "Electrical Engineer",
    "Chemical Engineer", "Industrial Engineer", "Materials Scientist",
    "Nanotechnologist", "Geneticist", "Biochemist", "Pharmacologist",
    "Toxicologist", "Epidemiologist", "Virologist", "Immunologist",
    "Neurologist", "Cardiologist", "Oncologist", "Pediatrician", "Surgeon",
    "Anesthesiologist", "Radiologist", "Pathologist", "Psychiatrist",
    "Dermatologist", "Ophthalmologist", "Urologist", "Gynecologist",
    "Obstetrician", "Endocrinologist", "Gastroenterologist", "Pulmonologist",
    "Rheumatologist", "Nephrologist", "Hematologist", "Geriatrician",
    "Emergency Medicine Physician", "Family Medicine Physician",
    "Internal Medicine Physician", "Sports Medicine Physician",
    "Forensic Scientist", "Crime Scene Investigator", "Detective",
    "FBI Agent", "CIA Agent", "Secret Service Agent", "Customs Officer",
    "Border Patrol Agent", "Air Traffic Controller", "Flight Attendant",
    "Aircraft Mechanic", "Automotive Mechanic", "Diesel Mechanic",
    "Marine Mechanic", "Bicycle Mechanic", "Locksmith", "Carpenter",
    "Mason", "Roofer", "Painter", "Welder", "Machinist", "CNC Operator",
    "Tool and Die Maker", "Quality Control Inspector", "Assembly Line Worker",
    "Forklift Operator", "Crane Operator", "Truck Driver", "Bus Driver",
    "Taxi Driver", "Uber/Lyft Driver", "Delivery Driver", "Courier",
    "Warehouse Worker", "Shipping and Receiving Clerk", "Inventory Manager",
    "Supply Chain Manager", "Logistics Coordinator", "Procurement Specialist",
    "Purchasing Manager", "Retail Store Manager", "Retail Sales Associate",
    "Cashier", "Bank Teller", "Loan Officer", "Mortgage Broker",
    "Investment Banker", "Stockbroker", "Financial Planner", "Actuary",
    "Underwriter", "Claims Adjuster", "Tax Preparer", "Auditor",
    "Bookkeeper", "Payroll Specialist", "Benefits Administrator",
    "Recruiter", "Training and Development Specialist", "Labor Relations Specialist",
    "Compensation and Benefits Manager", "Industrial-Organizational Psychologist",
    "Organizational Development Consultant", "Change Management Specialist",
    "Business Analyst", "Management Consultant", "Strategy Consultant",
    "Market Research Analyst", "Competitive Intelligence Analyst",
    "Brand Manager", "Public Relations Specialist", "Advertising Executive",
    "Copywriter", "Technical Writer", "Grant Writer", "Proposal Writer",
    "Speechwriter", "Translator", "Interpreter", "Court Reporter",
    "Paralegal", "Legal Assistant", "Judge", "Mediator", "Arbitrator",
    "Compliance Officer", "Ethics Officer", "Privacy Officer",
    "Risk Management Specialist", "Health and Safety Specialist",
    "Environmental Health and Safety Manager", "Sustainability Coordinator",
    "Urban Planner", "City Manager", "Mayor", "Politician", "Lobbyist",
    "Diplomat", "Foreign Service Officer", "Nonprofit Executive",
    "Fundraiser", "Volunteer Coordinator", "Community Outreach Coordinator",
    "Social Services Director", "Child Welfare Specialist", "Adoption Counselor",
    "Foster Care Specialist", "Substance Abuse Counselor", "Mental Health Counselor",
    "Marriage and Family Therapist", "School Counselor", "Career Counselor",
    "Rehabilitation Counselor", "Genetic Counselor", "Art Therapist",
    "Music Therapist", "Dance Therapist", "Drama Therapist", "Recreational Therapist",
    "Horticultural Therapist", "Animal-Assisted Therapist", "Hypnotherapist",
    "Life Coach", "Executive Coach", "Sports Coach", "Athletic Trainer",
    "Sports Agent", "Talent Agent", "Literary Agent", "Film Producer",
    "Film Director", "Screenwriter", "Actor", "Voice Actor", "Stunt Performer",
    "Dancer", "Choreographer", "Musician", "Singer", "Composer", "Conductor",
    "DJ", "Sound Engineer", "Lighting Technician", "Camera Operator",
    "Video Editor", "Animator", "Visual Effects Artist", "Game Designer",
    "Level Designer", "Narrative Designer", "Character Artist", "Concept Artist",
    "Illustrator", "Comic Book Artist", "Storyboard Artist", "Art Director",
    "Creative Director", "Fashion Stylist", "Personal Stylist", "Image Consultant",
    "Color Consultant", "Feng Shui Consultant", "Home Stager", "Party Planner",
    "Floral Designer", "Cake Decorator", "Chocolatier", "Sommelier",
    "Mixologist", "Food Critic", "Restaurant Critic", "Film Critic",
    "Book Critic", "Art Critic", "Music Critic", "Theater Critic",
    "Proofreader", "Copy Editor", "Developmental Editor", "Acquisitions Editor",
    "Literary Scout", "Archivist", "Curator", "Museum Technician",
    "Conservator", "Zookeeper", "Wildlife Rehabilitator", "Park Ranger",
    "Forester", "Farmer", "Agricultural Scientist", "Soil Scientist",
    "Crop Consultant", "Vintner", "Brewmaster", "Distiller", "Beekeeper",
    "Fisher", "Aquaculture Farmer", "Rancher", "Veterinary Technician",
    "Animal Trainer", "Pet Groomer", "Dog Walker", "Pet Sitter"
];